name: zhc learn-github-actions
run-name: zhc ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Make the script files executable & run a script
        run: |
          chmod +x my-script.sh
          my-script.sh
      - name: Run another script
        run: bash my-another-script.sh